/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ibm.account.api;

import com.ibm.account.model.Account;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-04-16T11:09:28.190Z[GMT]")

@Validated
@Api(value = "accounts", description = "the accounts API")
public interface AccountsApi {
    

    @ApiOperation(value = "getAccount", nickname = "getAccountUsingGET", notes = "", response = Account.class, tags={ "accounts-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Account.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/accounts/{accNumber}",
        produces = { "*/*" }, 
        method = RequestMethod.GET)
    ResponseEntity<Account> getAccountUsingGET(@ApiParam(value = "accNumber",required=true) @PathVariable("accNumber") String accNumber); 


    @ApiOperation(value = "getAccounts", nickname = "getAccountsUsingGET", notes = "", response = Account.class, tags={ "accounts-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Account.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/accounts",
        produces = { "*/*" }, 
        method = RequestMethod.GET)
    ResponseEntity<Account> getAccountsUsingGET(); 

}
